// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// argmaxLagIndexCpp
IntegerVector argmaxLagIndexCpp(NumericVector spdata, Function objfunc, NumericMatrix lagmat, bool minimize);
RcppExport SEXP _unisono_argmaxLagIndexCpp(SEXP spdataSEXP, SEXP objfuncSEXP, SEXP lagmatSEXP, SEXP minimizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type spdata(spdataSEXP);
    Rcpp::traits::input_parameter< Function >::type objfunc(objfuncSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lagmat(lagmatSEXP);
    Rcpp::traits::input_parameter< bool >::type minimize(minimizeSEXP);
    rcpp_result_gen = Rcpp::wrap(argmaxLagIndexCpp(spdata, objfunc, lagmat, minimize));
    return rcpp_result_gen;
END_RCPP
}
// argmaxLagIndexSqDiffCpp
IntegerVector argmaxLagIndexSqDiffCpp(NumericVector spdata, NumericMatrix lagmat, bool minimize);
RcppExport SEXP _unisono_argmaxLagIndexSqDiffCpp(SEXP spdataSEXP, SEXP lagmatSEXP, SEXP minimizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type spdata(spdataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lagmat(lagmatSEXP);
    Rcpp::traits::input_parameter< bool >::type minimize(minimizeSEXP);
    rcpp_result_gen = Rcpp::wrap(argmaxLagIndexSqDiffCpp(spdata, lagmat, minimize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_unisono_argmaxLagIndexCpp", (DL_FUNC) &_unisono_argmaxLagIndexCpp, 4},
    {"_unisono_argmaxLagIndexSqDiffCpp", (DL_FUNC) &_unisono_argmaxLagIndexSqDiffCpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_unisono(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
