# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Grid search using a user-supplied R objective function
#'
#' @description
#' Performs a grid search over spatial lag vectors using a custom,
#' user-supplied R objective function evaluated at each point.
#'
#' @param spdata A numeric vector representing the spatial field values.
#' @param objfunc A user-supplied R function taking `(z0, zlagged)` and returning numeric scores.
#' @param lagmat A numeric matrix where each row represents a lag vector.
#' @param minimize Logical. Should the objective function be minimized? Default is `false`.
#'
#' @return An IntegerVector containing the optimal lag index for each spatial location.
#'
#' @name argmaxLagIndexCpp
#' @keywords internal
#' @noRd
argmaxLagIndexCpp <- function(spdata, objfunc, lagmat, minimize = FALSE) {
    .Call(`_unisono_argmaxLagIndexCpp`, spdata, objfunc, lagmat, minimize)
}

#' Grid search using the native squared norm-difference objective
#'
#' @description
#' Performs an optimized grid search using the native squared norm-difference
#' objective. Bypasses R callbacks per grid point, making it substantially faster
#' and safe to parallelize.
#'
#' @param spdata A numeric vector representing the spatial field values.
#' @param lagmat A numeric matrix where each row represents a lag vector.
#' @param minimize Logical. Should the objective function be minimized? Default is `false`.
#'
#' @return An IntegerVector containing the optimal lag index for each spatial location.
#'
#' @name argmaxLagIndexSqDiffCpp
#' @keywords internal
#' @noRd
argmaxLagIndexSqDiffCpp <- function(spdata, lagmat, minimize = FALSE) {
    .Call(`_unisono_argmaxLagIndexSqDiffCpp`, spdata, lagmat, minimize)
}

